Clflags.include_dirs :=
  [ "/home/freenemya/.opam/system/lib/bytes"
  ; "/home/freenemya/.opam/system/lib/camomile"
  ; "/home/freenemya/.opam/system/lib/camomile/default_config"
  ; "/home/freenemya/.opam/system/lib/camomile/dyn"
  ; "/home/freenemya/.opam/system/lib/camomile/lib_default"
  ; "/home/freenemya/.opam/system/lib/camomile/library"
  ; "/home/freenemya/.opam/system/lib/findlib"
  ; "/home/freenemya/.opam/system/lib/lambda-term"
  ; "/home/freenemya/.opam/system/lib/lwt"
  ; "/home/freenemya/.opam/system/lib/lwt/unix"
  ; "/home/freenemya/.opam/system/lib/lwt_log"
  ; "/home/freenemya/.opam/system/lib/lwt_log/core"
  ; "/home/freenemya/.opam/system/lib/lwt_react"
  ; "/home/freenemya/.opam/system/lib/ocamlgraph"
  ; "/home/freenemya/.opam/system/lib/react"
  ; "/home/freenemya/.opam/system/lib/result"
  ; "/home/freenemya/.opam/system/lib/utop"
  ; "/home/freenemya/.opam/system/lib/zed"
  ; "/usr/lib/ocaml/compiler-libs"
  ; "/usr/lib/ocaml/threads"
  ; "/home/freenemya/Projet TG/aa/test_projet/_build/default/.projet_donjon.objs"
  ];

UTop_main.main ();
